architectures:
- AsteRISC:
    param_domains:
      __main__:
        param_file: benchmark_params.txt
        combine: both
        param_target_file: rtl/soc/soc_wrapper_top.sv
        start_delimiter: // <sim_override>
        stop_delimiter: \n  // </sim_override>
      Mul:
        param_dir: sim_params/rv32im_dhrystone
        combine: both
invariant_domains:
  MEM:
progress:
  file: log/progress/log
  regex: '(.*): ([0-9]+)%(.*)'
