
##############################################
# Settings for counter testbench
##############################################
---

# delimiters for parameter files
use_parameters: Yes
param_target_file: "rtl/soc/soc_wrapper_top.sv"
start_delimiter: "soc_wrapper_top #("
stop_delimiter: ")("

# override part of the parameters
override_parameters: Yes
override_param_target_file: "rtl/soc/soc_wrapper_top.sv"
override_param_file: "benchmark_params.txt"
override_start_delimiter: "  // -----------------------------------------------"
override_stop_delimiter: "  // -----------------------------------------------"
