
##############################################
# Odatix settings for custom freq synthesis
##############################################

# overwrite existing results
overwrite:        No   # overridden by -o / --overwrite

# prompt 'Continue? (Y/n)' after settings checks
ask_continue:     Yes  # overridden by -y / --noask

# exit monitor when all jobs are done
exit_when_done:   No   # overridden by -E / --exit

# size of the log history per job in the monitor
log_size_limit:   300  # overridden by --logsize

# maximum number of parallel jobs
nb_jobs:          8    # overridden by -j / --jobs

# targeted architectures
architectures: 

#--------------------------------------------#
# AsteRISC
#--------------------------------------------#
  
  - AsteRISC/* + MEM/1024I_1024D + Baseline/I + Mul/*