#**********************************************************************#
#                               AsteRISC                               #
#**********************************************************************#
#
# Copyright (C) 2022 Jonathan Saussereau
#
# This file is part of AsteRISC.
# AsteRISC is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# AsteRISC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with AsteRISC. If not, see <https://www.gnu.org/licenses/>.
#

import os
import sys
from datetime import datetime

######################################
# Settings
######################################

input_folder = './obj'
output_folder = './obj'
output_file = 'include_all.h'

# Check if the folder exists
if not os.path.exists(input_folder):
    print(f"The input folder '{input_folder}' does not exist.")
    sys.exit()

# Create the output folder if it doesn't exist
os.makedirs(output_folder, exist_ok=True)

# List of .h files in the folder
header_files = [file for file in os.listdir(input_folder) if file.endswith('.h')]

# If no .h file found, print a message and exit
if not header_files:
    print("No .h files found in the specified folder.")
    sys.exit()

# Get the current date and time
current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Create content for include_all.h file
include_content = f"""\
/**********************************************************************\\
*                               AsteRISC                               *
************************************************************************
*
* This file is automatically generated on {current_date}.
*
*/

#ifndef INCLUDE_ALL_H
#define INCLUDE_ALL_H

"""
for header_file in header_files:
    if header_file != output_file:
        include_content += f"#include \"{header_file}\"\n"

include_content += """\

#endif // INCLUDE_ALL_H
"""

# Path for include_all.h file
include_all_path = os.path.join(output_folder, output_file)

# Write content into include_all.h file
with open(include_all_path, "w") as include_all_file:
    include_all_file.write(include_content)

print(f"include_all.h file created successfully at location: {include_all_path}")
