
###########################################
# Parameter Domain - BranchPred           #
###########################################

start_delimiter: "  // <branch_pred>"
stop_delimiter: "  // </branch_pred>"
